[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "deep_sort_list_shreya"  
version = "1.0.4"  
description = "A recursive data parser to flatten and sort complex nested structures safely."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Shreya Singh" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[tool.hatch.build.targets.wheel]
only-include = ["deep_sort_list.py"]



